DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'freelance') THEN
        CREATE SCHEMA freelance;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS freelance."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'freelance') THEN
        CREATE SCHEMA freelance;
    END IF;
END $EF$;

CREATE SEQUENCE freelance.userseq START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE freelance.users (
    id integer NOT NULL,
    identity_guid character varying(250) NOT NULL,
    user_name character varying(250) NOT NULL,
    email_address character varying(250) NOT NULL,
    phone_number character varying(250) NOT NULL,
    hobby character varying(250),
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modified_by text NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE freelance.skillset (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    skill text NOT NULL,
    user_id integer,
    CONSTRAINT pk_skillset PRIMARY KEY (id),
    CONSTRAINT fk_skillset_user_user_id FOREIGN KEY (user_id) REFERENCES freelance.users (id)
);

CREATE INDEX ix_skillset_user_id ON freelance.skillset (user_id);

CREATE UNIQUE INDEX ix_users_identity_guid ON freelance.users (identity_guid);

INSERT INTO freelance."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20231221080420_CreateUserTable', '8.0.0');

